# Introduction to NumPy

NumPy stands for Numerical Python, a is very useful python library which provides an alternative data structure to Python Lists. The numpy arrays are compact, convenient and provides faster access in reading and writing items. the library consist of multi-dimensional array objects and a collection of routines for processing those arrays. It is open source! It is good alternative to MatLab and popular platform for technical computing.

In this session we will learn the basic construct of numpy with examples. The following topics will be discussed in this session: 

* Arrays
* Arrays indexing
* Datatypes
* Array Math
* Broadcasting
* Linear Algebra

Lets start by importing the numpy library using **import** statement.

In [1]:
#importing numpy library.
import numpy as np
# lets find out the version of installed numpy
print(np.__version__)

1.17.5


## NumPy Arrays

The most important object defined in NumPy is an N-Dimensional array type known as **ndarray**

The basic **ndarray** is created using an array function in NumPy as follows:
**numpy.array()**

The below examples illustrates the creation of NumPy array from list, tuples, etc.

#### 1. Create a NumPy array from list:

In [2]:
# Create list and convert it into numpy array 
a = np.array([1, 2, 3])
# Print a type of array a
print(type(a))
# Print the shape of the array
print(a.shape)
# Print individual elements in the array
print(a[0], a[1], a[2])
# Assign a value to a particular position in the array
a[0] = 5
print(a)
a

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


array([5, 2, 3])

#### 2. Create a NumPy array from tuple:

In [3]:
# lets create a tuple
my_tuple=(2+2j, -3.2, 5) # complex number
print(my_tuple)
# convert to numpy array
tuple_np=np.array(my_tuple)
print(tuple_np)
# all the elements of numpy are promoted to complex number, because neither int nor float is able to hold complex number.
# Numpy array elements will always have the same type.

((2+2j), -3.2, 5)
[ 2. +2.j -3.2+0.j  5. +0.j]


### Quiz: 
What will be the output of multiplying 4 to a python tuple and numpy array?

In [4]:
# Multiplying 4 with python tuple
my_tuple=(1,2,3)
## START YOUR CODE HERE ## (~ 1 line)
result=
print (result)

# Multiplying 4 with numpy array (~ 1 line)
result_np=
print (result_np)

SyntaxError: ignored

#### 3. Creation of numpy arrays using built-in functions
a) **arange()**:
Syntax:
*numpy.arange(start, stop, step, dtype)*

where: 
* start --> Start of an interval, default is 0
* stop --> End of an interval
* step --> spacing between the values, default is 1
* dtype --> Data type of the resulting ndarray

**Example:**


In [5]:
np_array=np.arange(4)    # This will create numpy array using arange()
print(np_array)
np_array1=np.arange(3,9)  # start=3 and stop=9
print(np_array1)
print(len(np_array1))
np_array2=np.arange(1,15,3) #start=1,stop=15,step=3
print(np_array2)

[0 1 2 3]
[3 4 5 6 7 8]
6
[ 1  4  7 10 13]


In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


b) **zeros()**: Returns a new array of specified size, filled with zeros.

Syntax:
**numpy.zeros(shape, dtype=float, order='C')**

where,
* shape --> Shape of an empty array in int or sequence of int
* dtype --> Data type of the resulting ndarray
* order --> C' for C-style row-major array, 'F' for FORTRAN style column-major array

Note: default dtype for zeros and ones function gives floating point values, while array function gives integer values

**Examples:**

In [9]:
a = np.zeros((2, 2)) # notice a '.' after every element represent floating point number
print(a)

[[0. 0.]
 [0. 0.]]


In [10]:
# create a 2D zeros array with dtype set to 'int32'
a = np.zeros((4, 4), dtype = np.int32)
print (a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


c) **ones()**: Returns a new array of specified size, filled with ones.

Syntax:
**numpy.ones(shape, dtype=float, order='C')**

where,
* shape --> Shape of an empty array in int or sequence of int
* dtype --> Data type of the resulting ndarray
* order --> C' for C-style row-major array, 'F' for FORTRAN style column-major array

**Examples:**

In [11]:
b = np.ones((1, 2))
print(b)

[[1. 1.]]


d) **full()**: Return a new array of given shape and type, filled with **fill_value**.

Syntax:
**numpy.full(shape, fill_value, dtype=None, order='C')**

where,
* shape --> Shape of an empty array in int or sequence of int
* fill_value --> a scalar value
* dtype --> Data type of the resulting ndarray (Optional)
* order --> C' for C-style row-major array, 'F' for FORTRAN style column-major array (Optional)

**Examples:**

In [12]:
c = np.full((2, 2), 7, dtype = np.int32, order = 'C')
print(c)

[[7 7]
 [7 7]]


e) **eye()**: Return a 2-D array with ones on the diagonal and zeros elsewhere, identity matrix.

Syntax:
**numpy.eye(N, M=None, k=0, dtype=(class 'float'), order='C')**

where,
* N --> Number of rows in the output
* M (int) --> Number of columns in the output. If None, defaults to N. (Optional)
* k (int) --> Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.(Optional)
* dtype --> Data-type of the returned array.
* order --> C' for C-style row-major array, 'F' for FORTRAN style column-major array (Optional)

**Examples:**

In [13]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


e) **random()**: Return random floats in the half-open interval [0.0, 1.0).

Syntax:

**numpy.random.random(size=none)** 

**numpy.random.random_sample()** 


where,
* Size --> Can be int, tuple of ints (Optional)

**Examples:**

In [14]:
np.random.random_sample()

0.9892559682639954

In [15]:
e = np.random.random((2, 2))
print(e)

[[0.09129306 0.6592758 ]
 [0.67903165 0.51066632]]


## Array indexing

Mechanism to access array elements

** Examples:**

In [16]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a[0, 1]) # remember numpy arrays are zeros indexed, syntax Array[row, col]
print(a[-1,-1])# negative indexing to access element from the end


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
12


**Task: Access the elements in the second row and print them**

In [17]:
# Access the second row and print it, Hint: Use the row number a index
print(a[2])
print(a[2, :])

[ 9 10 11 12]
[ 9 10 11 12]


In [18]:
# Access a sub-matrix with in a matrix by specifying a range, 
# Syntax: array[row-start:row-end, col-start:col-end]
# Row range: row-start : row-end
# Col range: Col-start : col-end
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [19]:
# Access single element two dimensional array and assign it to new value
b[0, 0] = 77
print(a[0, 1])
# another way to show element in 2-d array
a[0][1]

77


77

In [20]:
# access specific row and all columns
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1)
print(row_r2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[[5 6 7 8]]


In [21]:
# access specific column and all rows
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [22]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


### Accessing one element in 3-D array

In [0]:
array_3d=np.arange(24)  
array_3d.shape=(2,3,4) # 24
array_3d

In [0]:
# Access the last element and assign a new value of 44
array_3d[1,2,3]=44
array_3d

In [0]:
# Boolean masking

a = np.array([[1, 2], [3, 4], [5, 6]])
book_idx = (a > 2)
print(book_idx)
print(a[book_idx])
print(a[a > 2])

## Datatypes

In [23]:
x = np.array([1, 2])
print(x.dtype)

int64


In [24]:
x = np.array([1.0, 2.0])
print(x.dtype)

float64


In [25]:
x = np.array([1, 2], dtype=np.int64)
print(x.dtype)

int64


## Array mathematics

In [26]:
# Adding two arrays
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [27]:
# Array substraction
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [28]:
# Array multiplication
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [29]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [30]:
# Find Square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [31]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

219
219


In [32]:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [0]:
print(x.dot(y))
print(np.dot(x, y))

In [0]:
x = np.array([[1, 2], [3, 4]])
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

In [35]:
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [36]:
v = np.array([1, 2, 3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


In [37]:
# condition based on numpy array

x = np.array([1,2,1,3,2,2,5,3,3,5,6,7])
# where is the location of x==3
print(x[x==3])
# 
print(x[x<2])

print(np.where(x[x<6]))

print(np.where(x[x<4])[0])

[3 3 3]
[1 1]
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)
[0 1 2 3 4 5 6 7]


## Broadcasting

Broadcasting is a way of Numpy to work with arrays of different shapes. The smaller arrays are broacasted to larger array's size to make it compaitable for arithmetic operation.

In [38]:
# Multiply scalar is an example of scalar broadcasted to the larger array
array_3D=np.arange(40)
array_3D.shape=(2,5,4)
print(array_3D)

#
2+array_3D*5

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]]


array([[[  2,   7,  12,  17],
        [ 22,  27,  32,  37],
        [ 42,  47,  52,  57],
        [ 62,  67,  72,  77],
        [ 82,  87,  92,  97]],

       [[102, 107, 112, 117],
        [122, 127, 132, 137],
        [142, 147, 152, 157],
        [162, 167, 172, 177],
        [182, 187, 192, 197]]])

In [39]:
# Broading along particular axis Lets take above example

print(array_3D.sum())
array_3D.sum(axis=0)        # along 0 axis result in resultant array of size 5,4
array_3D.sum(axis=1)         # along 1 axis result in resultant array of size 2,4 
array_3D.sum(axis=2)          # along 2 axis result in resultant array of size 2,5


780


array([[  6,  22,  38,  54,  70],
       [ 86, 102, 118, 134, 150]])

In [40]:
# Rules for broadcasting for two matrix is that the dimension should be compaitable 
# 1. Compaitable mean if one the dimension is 1
 
#1
x = np.ones((3,4))
print(x.shape)
y = np.arange(4)
print(y.shape)
z=x+y

(3, 4)
(4,)


## Linear Algebra using Numpy np.linalg

In [41]:
# Matrix determinant
a = np.array([[6,-5, 4, 4], [1,5,1,2], [4,5,6,7],[2,3,4,5]])
np.linalg.det(a)


55.99999999999992

In [42]:
# Matrix Inverse
A = np.array([[2,3],[3,5]])
invA = np.linalg.inv(A)
invA

array([[ 5., -3.],
       [-3.,  2.]])

In [44]:
#  A*invA=invA*A=Identity matrix
#  Lets verify
np.round(np.dot(A,invA))

array([[1., 0.],
       [0., 1.]])

In [45]:
# Find the eigen value and eigen vector
B = np.diag((4,3,2))
x,y = np.linalg.eig(B)
print(x)
print(y)

[4. 3. 2.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Reference:

1. Numpy CheatSheet available at the following link
https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

2. Installation: https://www.tutorialspoint.com/numpy/numpy_environment.htm